### ISSUE TITLE
specify  buildpacks

### ISSUE THREAD

**Issue by luto65** [cloudfoundry-incubator/multiapps-cli-plugin#37]
In a manifest.yml one can specify specific buildpacks requirements with the following syntax.

  buildpacks:
   -  https://github.com/cloudfoundry/nodejs-buildpack.git#v1.6.27

I've tried to do that with the mta.yaml but I got error message that let me understand that this feature is either not implemented or has a different syntax.

Could you please instruct ?

**Comment by theghost5800** [comment]
Could you please provide your mta.yaml descriptor. You can upload it at [Gist](https://gist.github.com/)

**Comment by luto65** [comment]
I found an example on how to do that

```
modules:
 - name: xxxx
   parameters:
      buildpacks: 
     - https://github.com/cloudfoundry/nodejs-buildpack.git#v1.6.27

```
