### ISSUE TITLE
Console output doesn't count services correctly

### ISSUE THREAD

**Issue by IObert** [cloudfoundry-incubator/multiapps-cli-plugin#76]
### Description
When I'm deploying a mta, which uses multiple services (>2), the console doesn't indicate how many services have been created yet. It only shows "0 of 1" multiple times.
Here's an example of this outout:
```
 cf deploy city-explorer-demo-app_1.1.0.mtar
Deploying multi-target app archive city-explorer-demo-app_1.1.0.mtar in org D00000trial_d00000 / space dev as marius.obert@sap.com...

Uploading 1 files...
  /home/adele/city-explorer-demo-app_1.1.0.mtar
OK
Deploying in org "D00000trial_d00000" and space "dev"
Detected MTA schema version: "2"
No deployed MTA detected - this is initial deployment
Detected new MTA version: "1.1.0"
Processing service "azure-blob-storage"...
Creating service "azure-blob-storage" from MTA resource "azure-blob-storage"...
Processing service "city-hdi-container"...
Creating service "city-hdi-container" from MTA resource "city-hdi-container"...
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
1 of 1 done
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
0 of 1 done, (1 creating)
1 of 1 done
Creating application "city-app-router" from MTA module "city-app-router"...
Uploading application "city-app-router"...
Scaling application "city-app-router" to "1" instances...
Staging application "city-app-router"...
Application "city-app-router" staged
Starting application "city-app-router"...
...
```

### Your environment
*	MultiApps Controller version -  
*	MultiApps CF CLI Plugin version - 
*	which CF vendor is used -  SAP Cloud Platform Trial
*	which backing services are used - HANA HDI trial, and Azure storage account via OSB for Azure

### Steps to reproduce
Tell us how to reproduce this issue:  Here's the descriptor file (the issue might be related that both services come from two service brokers):
```
_schema-version: 2.0.0
ID: city-explorer-demo-app
version: 1.1.0
modules:
  - name: city-app-router
    type: approuter.nodejs
    path: app
    parameters:
      disk-quota: 256M
      memory: 256M
    requires:
      - name: srv_api
        group: destinations
        properties:
          forwardAuthToken: true
          strictSSL: false
          name: srv_api
          url: ~{url}
      - name: uploader_api
        group: destinations
        properties:
          forwardAuthToken: true
          strictSSL: false
          name: uploader_api
          url: ~{url}
  - name: city-app-db
    type: hdb
    path: db
    parameters:
      memory: 256M
      disk-quota: 512M
    requires:
      - name: city-hdi-container
  - name: city-cap-srv
    type: nodejs
    path: srv
    parameters:
      memory: 512M
      disk-quota: 512M
    provides:
      - name: srv_api
        properties:
          url: ${default-url}
    requires:
      - name: city-hdi-container
  - name: city-image-uploader
    type: nodejs
    path: uploader
    parameters:
      memory: 512M
      disk-quota: 512M
    provides:
      - name: uploader_api
        properties:
          url: ${default-url}
    requires:
      - name: azure-blob-storage
resources:
  - name: city-hdi-container
    type: com.sap.xs.hdi-container
    properties:
      hdi-container-name: ${service-name}
    parameters:
      service: hanatrial
  - name: azure-blob-storage
    type: org.cloudfoundry.managed-service
    parameters:
      service: azure-storage-blob-storage-account-and-container
      service-plan: all-in-one
      config:
        location: "northeurope"
        resourceGroup: "SAPTechEd"
        accessTier: "Cool"

```
